services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/Praveen-pk-pro/n8n
    branch: master
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: pravo
      - key: N8N_BASIC_AUTH_PASSWORD
        value: timeisgolddamapla
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
